/**
 * fs-blocks/index-block – registration
 */
import { registerBlockType } from '@wordpress/blocks';
import metadata from './block.json';
import Edit from './edit';
import { generateAttributes } from '../utils/helpers';

/* merge slider‑range attributes generated by the helper */
const attributes = {
	...metadata.attributes,
	...generateAttributes(), // padding / margin / negative‑margin, width…
};

registerBlockType( metadata.name, {
	title: metadata.title,
	category: metadata.category,
	parent: metadata.parent,
	attributes,

	edit,
	save: () => null, // dynamic – rendered in PHP
} );

function edit( props ) {
	return <Edit { ...props } />;
}
